


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html id="htmlId">
<head>
  <title>Coverage Report :: CustomExceptionHandler</title>
  <style type="text/css">
    @import "../../.css/coverage.css";
  </style>
</head>

<body>
<div class="header"></div>

<div class="content">
<div class="breadCrumbs">
    [ <a href="../../index.html">all classes</a> ]
    [ <a href="../index.html">com.infy.WikiDocsProject.Exception</a> ]
</div>

<h1>Coverage Summary for Class: CustomExceptionHandler (com.infy.WikiDocsProject.Exception)</h1>

<table class="coverageStats">
<tr>
  <th class="name">Class</th>
<th class="coverageStat 
">
  Class, %
</th>
<th class="coverageStat 
">
  Method, %
</th>
<th class="coverageStat 
">
  Line, %
</th>
</tr>
<tr>
  <td class="name">CustomExceptionHandler</td>
<td class="coverageStat">
  <span class="percent">
    100%
  </span>
  <span class="absValue">
    (1/ 1)
  </span>
</td>
<td class="coverageStat">
  <span class="percent">
    9.1%
  </span>
  <span class="absValue">
    (2/ 22)
  </span>
</td>
<td class="coverageStat">
  <span class="percent">
    14.8%
  </span>
  <span class="absValue">
    (4/ 27)
  </span>
</td>
</tr>

</table>

<br/>
<br/>


<div class="sourceCode"><i>1</i>&nbsp;package com.infy.WikiDocsProject.Exception;
<i>2</i>&nbsp;
<i>3</i>&nbsp;import com.infy.WikiDocsProject.Model.ErrorMessage;
<i>4</i>&nbsp;import org.springframework.beans.factory.annotation.Autowired;
<i>5</i>&nbsp;import org.springframework.core.env.Environment;
<i>6</i>&nbsp;import org.springframework.http.HttpStatus;
<i>7</i>&nbsp;import org.springframework.http.ResponseEntity;
<i>8</i>&nbsp;import org.springframework.security.authentication.BadCredentialsException;
<i>9</i>&nbsp;import org.springframework.security.core.userdetails.UsernameNotFoundException;
<i>10</i>&nbsp;import org.springframework.web.bind.annotation.ExceptionHandler;
<i>11</i>&nbsp;import org.springframework.web.bind.annotation.RestControllerAdvice;
<i>12</i>&nbsp;import org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler;
<i>13</i>&nbsp;import lombok.extern.slf4j.Slf4j;
<i>14</i>&nbsp;import static org.springframework.http.HttpStatus.*;
<i>15</i>&nbsp;
<b class="fc"><i>16</i>&nbsp;@Slf4j</b>
<i>17</i>&nbsp;@RestControllerAdvice
<i>18</i>&nbsp;public class CustomExceptionHandler extends ResponseEntityExceptionHandler {
<i>19</i>&nbsp;
<i>20</i>&nbsp;    @Autowired
<i>21</i>&nbsp;    private final Environment environment;
<i>22</i>&nbsp;
<b class="fc"><i>23</i>&nbsp;    public CustomExceptionHandler(Environment environment) {</b>
<b class="fc"><i>24</i>&nbsp;        this.environment = environment;</b>
<b class="fc"><i>25</i>&nbsp;    }</b>
<i>26</i>&nbsp;
<i>27</i>&nbsp;    @ExceptionHandler({ApprovingArticleIsApprovedException.class})
<i>28</i>&nbsp;    public ResponseEntity&lt;ErrorMessage&gt; approvingArticleIsApprovedException(ApprovingArticleIsApprovedException e) {
<b class="nc"><i>29</i>&nbsp;        return error(BAD_REQUEST, e);</b>
<i>30</i>&nbsp;    }
<i>31</i>&nbsp;
<i>32</i>&nbsp;    @ExceptionHandler({ApprovingArticleIsDiscardedException.class})
<i>33</i>&nbsp;    public ResponseEntity&lt;ErrorMessage&gt; approvingArticleIsDiscardedException(ApprovingArticleIsDiscardedException e) {
<b class="nc"><i>34</i>&nbsp;        return error(BAD_REQUEST, e);</b>
<i>35</i>&nbsp;    }
<i>36</i>&nbsp;
<i>37</i>&nbsp;    @ExceptionHandler({ApprovingArticleIsInitialException.class})
<i>38</i>&nbsp;    public ResponseEntity&lt;ErrorMessage&gt; approvingArticleIsInitialException(ApprovingArticleIsInitialException e) {
<b class="nc"><i>39</i>&nbsp;        return error(BAD_REQUEST, e);</b>
<i>40</i>&nbsp;    }
<i>41</i>&nbsp;
<i>42</i>&nbsp;    @ExceptionHandler({ApprovingArticleIsStillRejectedException.class})
<i>43</i>&nbsp;    public ResponseEntity&lt;ErrorMessage&gt; approvingArticleIsStillRejectedException(ApprovingArticleIsStillRejectedException e) {
<b class="nc"><i>44</i>&nbsp;        return error(BAD_REQUEST, e);</b>
<i>45</i>&nbsp;    }
<i>46</i>&nbsp;
<i>47</i>&nbsp;    @ExceptionHandler({RejectingArticleIsApprovedException.class})
<i>48</i>&nbsp;    public ResponseEntity&lt;ErrorMessage&gt; rejectingArticleIsApprovedException(RejectingArticleIsApprovedException e) {
<b class="nc"><i>49</i>&nbsp;        return error(BAD_REQUEST, e);</b>
<i>50</i>&nbsp;    }
<i>51</i>&nbsp;
<i>52</i>&nbsp;    @ExceptionHandler({RejectingArticleIsDiscardedException.class})
<i>53</i>&nbsp;    public ResponseEntity&lt;ErrorMessage&gt; rejectingArticleIsDiscardedException(RejectingArticleIsDiscardedException e) {
<b class="nc"><i>54</i>&nbsp;        return error(BAD_REQUEST, e);</b>
<i>55</i>&nbsp;    }
<i>56</i>&nbsp;
<i>57</i>&nbsp;    @ExceptionHandler({RejectingArticleIsInitialException.class})
<i>58</i>&nbsp;    public ResponseEntity&lt;ErrorMessage&gt; rejectingArticleIsInitialException(RejectingArticleIsInitialException e) {
<b class="nc"><i>59</i>&nbsp;        return error(BAD_REQUEST, e);</b>
<i>60</i>&nbsp;    }
<i>61</i>&nbsp;
<i>62</i>&nbsp;    @ExceptionHandler({RejectingArticleIsStillRejectedException.class})
<i>63</i>&nbsp;    public ResponseEntity&lt;ErrorMessage&gt; rejectingArticleIsStillRejectedException(RejectingArticleIsStillRejectedException e) {
<b class="nc"><i>64</i>&nbsp;        return error(BAD_REQUEST, e);</b>
<i>65</i>&nbsp;    }
<i>66</i>&nbsp;
<i>67</i>&nbsp;    @ExceptionHandler({SubmittingArticleIsApprovedException.class})
<i>68</i>&nbsp;    public ResponseEntity&lt;ErrorMessage&gt; submittingArticleIsApprovedException(SubmittingArticleIsApprovedException e) {
<b class="nc"><i>69</i>&nbsp;        return error(BAD_REQUEST, e);</b>
<i>70</i>&nbsp;    }
<i>71</i>&nbsp;
<i>72</i>&nbsp;    @ExceptionHandler({SubmittingArticleIsBetaException.class})
<i>73</i>&nbsp;    public ResponseEntity&lt;ErrorMessage&gt; submittingArticleIsBetaException(SubmittingArticleIsBetaException e) {
<b class="nc"><i>74</i>&nbsp;        return error(BAD_REQUEST, e);</b>
<i>75</i>&nbsp;    }
<i>76</i>&nbsp;
<i>77</i>&nbsp;    @ExceptionHandler({SubmittingArticleIsDiscardedException.class})
<i>78</i>&nbsp;    public ResponseEntity&lt;ErrorMessage&gt; submittingArticleIsDiscardedException(SubmittingArticleIsDiscardedException e) {
<b class="nc"><i>79</i>&nbsp;        return error(BAD_REQUEST, e);</b>
<i>80</i>&nbsp;    }
<i>81</i>&nbsp;
<i>82</i>&nbsp;    @ExceptionHandler({ArticleNotFoundException.class})
<i>83</i>&nbsp;    public ResponseEntity&lt;ErrorMessage&gt; articleNotFoundException(ArticleNotFoundException e) {
<b class="nc"><i>84</i>&nbsp;        return error(NOT_FOUND, e);</b>
<i>85</i>&nbsp;    }
<i>86</i>&nbsp;
<i>87</i>&nbsp;    @ExceptionHandler({UserNotFoundException.class})
<i>88</i>&nbsp;    public ResponseEntity&lt;ErrorMessage&gt; userNotFoundException(UserNotFoundException e) {
<b class="nc"><i>89</i>&nbsp;        return error(NOT_FOUND, e);</b>
<i>90</i>&nbsp;    }
<i>91</i>&nbsp;
<i>92</i>&nbsp;    @ExceptionHandler({UserAlreadyExistsException.class})
<i>93</i>&nbsp;    public ResponseEntity&lt;ErrorMessage&gt; userAlreadyExistsException(UserAlreadyExistsException e){
<b class="nc"><i>94</i>&nbsp;        return error(CONFLICT, e);</b>
<i>95</i>&nbsp;    }
<i>96</i>&nbsp;
<i>97</i>&nbsp;    @ExceptionHandler({PasswordIncorrectException.class})
<i>98</i>&nbsp;    public ResponseEntity&lt;ErrorMessage&gt; passwordIncorrectException(PasswordIncorrectException e) {
<b class="nc"><i>99</i>&nbsp;        return error(UNAUTHORIZED, e);</b>
<i>100</i>&nbsp;    }
<i>101</i>&nbsp;
<i>102</i>&nbsp;    @ExceptionHandler({UserAlreadyInvitedException.class})
<i>103</i>&nbsp;    public ResponseEntity&lt;ErrorMessage&gt; userAlreadyInvitedException(UserAlreadyInvitedException e) {
<b class="nc"><i>104</i>&nbsp;        return error(CONFLICT, e);</b>
<i>105</i>&nbsp;    }
<i>106</i>&nbsp;
<i>107</i>&nbsp;
<i>108</i>&nbsp;    @ExceptionHandler({UsernameNotFoundException.class})
<i>109</i>&nbsp;    public ResponseEntity&lt;ErrorMessage&gt; UsernameNotFoundException(UsernameNotFoundException e) {
<b class="nc"><i>110</i>&nbsp;        return error(UNAUTHORIZED, e);</b>
<i>111</i>&nbsp;    }
<i>112</i>&nbsp;
<i>113</i>&nbsp;    @ExceptionHandler({BadCredentialsException.class})
<i>114</i>&nbsp;    public ResponseEntity&lt;ErrorMessage&gt; BadCredentialsException(BadCredentialsException e) {
<b class="nc"><i>115</i>&nbsp;        return error(UNAUTHORIZED, e);</b>
<i>116</i>&nbsp;    }
<i>117</i>&nbsp;
<i>118</i>&nbsp;    @ExceptionHandler({RuntimeException.class})
<i>119</i>&nbsp;    public ResponseEntity&lt;ErrorMessage&gt; exception(RuntimeException e) {
<b class="nc"><i>120</i>&nbsp;        return error(INTERNAL_SERVER_ERROR, e);</b>
<i>121</i>&nbsp;    }
<i>122</i>&nbsp;
<i>123</i>&nbsp;    private ResponseEntity&lt;ErrorMessage&gt; error(HttpStatus status, Exception e) {
<b class="nc"><i>124</i>&nbsp;        log.error(&quot;The following exception occurred during processing:  &quot;, e);</b>
<b class="nc"><i>125</i>&nbsp;        log.info(environment.getProperty(e.getMessage()));</b>
<b class="nc"><i>126</i>&nbsp;        ErrorMessage error = new ErrorMessage(status.value(), environment.getProperty(e.getMessage()));</b>
<b class="nc"><i>127</i>&nbsp;        return new ResponseEntity&lt;&gt;(error, status);</b>
<i>128</i>&nbsp;    }
<i>129</i>&nbsp;}
</div>
</div>

<div class="footer">
    
    <div style="float:right;">generated on 2020-03-24 21:41</div>
</div>
</body>
</html>
